spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=inventory_db

# Basic Auth credentials
spring.security.user.name=admin
spring.security.user.password=admin123
